version: "3.9"

services:
  web:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    environment:
      - MYSQL_HOST=192.168.100.155
      - MYSQL_USER=userdb
      - MYSQL_PASSWORD=Zo0&p,12yT$7
      - MYSQL_DB=db_webapp
    depends_on:
      - db

  db:
    image: mysql:9.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Psw*427Ah.1z
      MYSQL_DATABASE: db_webapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
